### ISSUE TITLE
vgg16

### ISSUE THREAD

**Issue by sunithak** [Spandan-Madan/Pytorch_fine_tuning_Tutorial#4] opened 2017-12-05 14:31 UTC
hello, this is a nice tutorial. I would like to use vgg16. it is not working on this data when i apply.

**Comment by Spandan-Madan** [comment] 2018-07-27 04:09
Hi @sunithak,

Can you give more information? What is the error, what you tried etc. If you add code snippet of what you tried and snippet of error trace then people who visit this repo (and me) can try to help you out.

If it's solved, please let me know so I can close the issue.

**Comment by Spandan-Madan** [comment] 2018-09-11 21:57
Closing thread as there's no response on it, in case the issue is persisting, please reopen the issue!

**Closed by Spandan-Madan** 2018-09-11 21:57 UTC
